//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookland
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int BookId { get; set; }
        public int ReaderId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
